apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-ingress
  sources:
  - repoURL: https://github.com/dzhunli/agrocd_tests.git
    targetRevision: HEAD
    path: manifests/nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  
